// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// AttachmentModelsColumns holds the columns for the "attachment_models" table.
	AttachmentModelsColumns = []*schema.Column{
		{Name: "attachment_id", Type: field.TypeUUID},
		{Name: "link", Type: field.TypeString},
		{Name: "ticket_id", Type: field.TypeUUID},
	}
	// AttachmentModelsTable holds the schema information for the "attachment_models" table.
	AttachmentModelsTable = &schema.Table{
		Name:       "attachment_models",
		Columns:    AttachmentModelsColumns,
		PrimaryKey: []*schema.Column{AttachmentModelsColumns[0]},
	}
	// CategoryModelsColumns holds the columns for the "category_models" table.
	CategoryModelsColumns = []*schema.Column{
		{Name: "category_id", Type: field.TypeUUID},
		{Name: "name", Type: field.TypeString},
		{Name: "tenant_id", Type: field.TypeUUID},
	}
	// CategoryModelsTable holds the schema information for the "category_models" table.
	CategoryModelsTable = &schema.Table{
		Name:       "category_models",
		Columns:    CategoryModelsColumns,
		PrimaryKey: []*schema.Column{CategoryModelsColumns[0]},
	}
	// TenantModelsColumns holds the columns for the "tenant_models" table.
	TenantModelsColumns = []*schema.Column{
		{Name: "tenant_id", Type: field.TypeUUID},
		{Name: "tenant_name", Type: field.TypeString, Unique: true},
		{Name: "status", Type: field.TypeInt},
	}
	// TenantModelsTable holds the schema information for the "tenant_models" table.
	TenantModelsTable = &schema.Table{
		Name:       "tenant_models",
		Columns:    TenantModelsColumns,
		PrimaryKey: []*schema.Column{TenantModelsColumns[0]},
	}
	// ThreadModelsColumns holds the columns for the "thread_models" table.
	ThreadModelsColumns = []*schema.Column{
		{Name: "thread_id", Type: field.TypeUUID},
		{Name: "body", Type: field.TypeString, Unique: true},
		{Name: "status", Type: field.TypeInt},
	}
	// ThreadModelsTable holds the schema information for the "thread_models" table.
	ThreadModelsTable = &schema.Table{
		Name:       "thread_models",
		Columns:    ThreadModelsColumns,
		PrimaryKey: []*schema.Column{ThreadModelsColumns[0]},
	}
	// TicketModelsColumns holds the columns for the "ticket_models" table.
	TicketModelsColumns = []*schema.Column{
		{Name: "ticket_id", Type: field.TypeUUID},
		{Name: "user_id", Type: field.TypeUUID},
		{Name: "tenant_id", Type: field.TypeUUID},
		{Name: "subject", Type: field.TypeString},
		{Name: "body", Type: field.TypeString},
		{Name: "category", Type: field.TypeUUID},
		{Name: "label", Type: field.TypeString},
		{Name: "assignee_id", Type: field.TypeUUID},
		{Name: "severity", Type: field.TypeInt},
		{Name: "status", Type: field.TypeInt},
		{Name: "time", Type: field.TypeTime},
	}
	// TicketModelsTable holds the schema information for the "ticket_models" table.
	TicketModelsTable = &schema.Table{
		Name:       "ticket_models",
		Columns:    TicketModelsColumns,
		PrimaryKey: []*schema.Column{TicketModelsColumns[0]},
	}
	// UserModelsColumns holds the columns for the "user_models" table.
	UserModelsColumns = []*schema.Column{
		{Name: "user_id", Type: field.TypeUUID},
		{Name: "user_name", Type: field.TypeString, Unique: true},
		{Name: "pswd", Type: field.TypeString},
		{Name: "tenant_id", Type: field.TypeUUID},
		{Name: "role", Type: field.TypeString},
	}
	// UserModelsTable holds the schema information for the "user_models" table.
	UserModelsTable = &schema.Table{
		Name:       "user_models",
		Columns:    UserModelsColumns,
		PrimaryKey: []*schema.Column{UserModelsColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		AttachmentModelsTable,
		CategoryModelsTable,
		TenantModelsTable,
		ThreadModelsTable,
		TicketModelsTable,
		UserModelsTable,
	}
)

func init() {
}
