// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// AttachmentModel is the predicate function for attachmentmodel builders.
type AttachmentModel func(*sql.Selector)

// CategoryModel is the predicate function for categorymodel builders.
type CategoryModel func(*sql.Selector)

// TenantModel is the predicate function for tenantmodel builders.
type TenantModel func(*sql.Selector)

// ThreadModel is the predicate function for threadmodel builders.
type ThreadModel func(*sql.Selector)

// TicketModel is the predicate function for ticketmodel builders.
type TicketModel func(*sql.Selector)

// UserModel is the predicate function for usermodel builders.
type UserModel func(*sql.Selector)
