package gql

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.36

import (
	"context"
	"fmt"
)

// Tickets is the resolver for the tickets field.
func (r *queryResolver) Tickets(ctx context.Context) (string, error) {
	panic(fmt.Errorf("not implemented: Tickets - tickets"))
}

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
