// Code generated by ent, DO NOT EDIT.

package threadmodel

import (
	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the threadmodel type in the database.
	Label = "thread_model"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "thread_id"
	// FieldBody holds the string denoting the body field in the database.
	FieldBody = "body"
	// FieldTime holds the string denoting the time field in the database.
	FieldTime = "time"
	// FieldTicketUUID holds the string denoting the ticket_uuid field in the database.
	FieldTicketUUID = "ticket_uuid"
	// FieldSource holds the string denoting the source field in the database.
	FieldSource = "source"
	// Table holds the table name of the threadmodel in the database.
	Table = "thread_models"
)

// Columns holds all SQL columns for threadmodel fields.
var Columns = []string{
	FieldID,
	FieldBody,
	FieldTime,
	FieldTicketUUID,
	FieldSource,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// OrderOption defines the ordering options for the ThreadModel queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByBody orders the results by the body field.
func ByBody(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBody, opts...).ToFunc()
}

// ByTime orders the results by the time field.
func ByTime(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTime, opts...).ToFunc()
}

// ByTicketUUID orders the results by the ticket_uuid field.
func ByTicketUUID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTicketUUID, opts...).ToFunc()
}

// BySource orders the results by the source field.
func BySource(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSource, opts...).ToFunc()
}
