// Code generated by ent, DO NOT EDIT.

package threadmodel

import (
	"kapt/kapt/gql/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.ThreadModel {
	return predicate.ThreadModel(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.ThreadModel {
	return predicate.ThreadModel(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.ThreadModel {
	return predicate.ThreadModel(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.ThreadModel {
	return predicate.ThreadModel(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.ThreadModel {
	return predicate.ThreadModel(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.ThreadModel {
	return predicate.ThreadModel(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.ThreadModel {
	return predicate.ThreadModel(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.ThreadModel {
	return predicate.ThreadModel(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.ThreadModel {
	return predicate.ThreadModel(sql.FieldLTE(FieldID, id))
}

// Body applies equality check predicate on the "body" field. It's identical to BodyEQ.
func Body(v string) predicate.ThreadModel {
	return predicate.ThreadModel(sql.FieldEQ(FieldBody, v))
}

// Time applies equality check predicate on the "time" field. It's identical to TimeEQ.
func Time(v time.Time) predicate.ThreadModel {
	return predicate.ThreadModel(sql.FieldEQ(FieldTime, v))
}

// TicketUUID applies equality check predicate on the "ticket_uuid" field. It's identical to TicketUUIDEQ.
func TicketUUID(v uuid.UUID) predicate.ThreadModel {
	return predicate.ThreadModel(sql.FieldEQ(FieldTicketUUID, v))
}

// Source applies equality check predicate on the "source" field. It's identical to SourceEQ.
func Source(v string) predicate.ThreadModel {
	return predicate.ThreadModel(sql.FieldEQ(FieldSource, v))
}

// BodyEQ applies the EQ predicate on the "body" field.
func BodyEQ(v string) predicate.ThreadModel {
	return predicate.ThreadModel(sql.FieldEQ(FieldBody, v))
}

// BodyNEQ applies the NEQ predicate on the "body" field.
func BodyNEQ(v string) predicate.ThreadModel {
	return predicate.ThreadModel(sql.FieldNEQ(FieldBody, v))
}

// BodyIn applies the In predicate on the "body" field.
func BodyIn(vs ...string) predicate.ThreadModel {
	return predicate.ThreadModel(sql.FieldIn(FieldBody, vs...))
}

// BodyNotIn applies the NotIn predicate on the "body" field.
func BodyNotIn(vs ...string) predicate.ThreadModel {
	return predicate.ThreadModel(sql.FieldNotIn(FieldBody, vs...))
}

// BodyGT applies the GT predicate on the "body" field.
func BodyGT(v string) predicate.ThreadModel {
	return predicate.ThreadModel(sql.FieldGT(FieldBody, v))
}

// BodyGTE applies the GTE predicate on the "body" field.
func BodyGTE(v string) predicate.ThreadModel {
	return predicate.ThreadModel(sql.FieldGTE(FieldBody, v))
}

// BodyLT applies the LT predicate on the "body" field.
func BodyLT(v string) predicate.ThreadModel {
	return predicate.ThreadModel(sql.FieldLT(FieldBody, v))
}

// BodyLTE applies the LTE predicate on the "body" field.
func BodyLTE(v string) predicate.ThreadModel {
	return predicate.ThreadModel(sql.FieldLTE(FieldBody, v))
}

// BodyContains applies the Contains predicate on the "body" field.
func BodyContains(v string) predicate.ThreadModel {
	return predicate.ThreadModel(sql.FieldContains(FieldBody, v))
}

// BodyHasPrefix applies the HasPrefix predicate on the "body" field.
func BodyHasPrefix(v string) predicate.ThreadModel {
	return predicate.ThreadModel(sql.FieldHasPrefix(FieldBody, v))
}

// BodyHasSuffix applies the HasSuffix predicate on the "body" field.
func BodyHasSuffix(v string) predicate.ThreadModel {
	return predicate.ThreadModel(sql.FieldHasSuffix(FieldBody, v))
}

// BodyEqualFold applies the EqualFold predicate on the "body" field.
func BodyEqualFold(v string) predicate.ThreadModel {
	return predicate.ThreadModel(sql.FieldEqualFold(FieldBody, v))
}

// BodyContainsFold applies the ContainsFold predicate on the "body" field.
func BodyContainsFold(v string) predicate.ThreadModel {
	return predicate.ThreadModel(sql.FieldContainsFold(FieldBody, v))
}

// TimeEQ applies the EQ predicate on the "time" field.
func TimeEQ(v time.Time) predicate.ThreadModel {
	return predicate.ThreadModel(sql.FieldEQ(FieldTime, v))
}

// TimeNEQ applies the NEQ predicate on the "time" field.
func TimeNEQ(v time.Time) predicate.ThreadModel {
	return predicate.ThreadModel(sql.FieldNEQ(FieldTime, v))
}

// TimeIn applies the In predicate on the "time" field.
func TimeIn(vs ...time.Time) predicate.ThreadModel {
	return predicate.ThreadModel(sql.FieldIn(FieldTime, vs...))
}

// TimeNotIn applies the NotIn predicate on the "time" field.
func TimeNotIn(vs ...time.Time) predicate.ThreadModel {
	return predicate.ThreadModel(sql.FieldNotIn(FieldTime, vs...))
}

// TimeGT applies the GT predicate on the "time" field.
func TimeGT(v time.Time) predicate.ThreadModel {
	return predicate.ThreadModel(sql.FieldGT(FieldTime, v))
}

// TimeGTE applies the GTE predicate on the "time" field.
func TimeGTE(v time.Time) predicate.ThreadModel {
	return predicate.ThreadModel(sql.FieldGTE(FieldTime, v))
}

// TimeLT applies the LT predicate on the "time" field.
func TimeLT(v time.Time) predicate.ThreadModel {
	return predicate.ThreadModel(sql.FieldLT(FieldTime, v))
}

// TimeLTE applies the LTE predicate on the "time" field.
func TimeLTE(v time.Time) predicate.ThreadModel {
	return predicate.ThreadModel(sql.FieldLTE(FieldTime, v))
}

// TicketUUIDEQ applies the EQ predicate on the "ticket_uuid" field.
func TicketUUIDEQ(v uuid.UUID) predicate.ThreadModel {
	return predicate.ThreadModel(sql.FieldEQ(FieldTicketUUID, v))
}

// TicketUUIDNEQ applies the NEQ predicate on the "ticket_uuid" field.
func TicketUUIDNEQ(v uuid.UUID) predicate.ThreadModel {
	return predicate.ThreadModel(sql.FieldNEQ(FieldTicketUUID, v))
}

// TicketUUIDIn applies the In predicate on the "ticket_uuid" field.
func TicketUUIDIn(vs ...uuid.UUID) predicate.ThreadModel {
	return predicate.ThreadModel(sql.FieldIn(FieldTicketUUID, vs...))
}

// TicketUUIDNotIn applies the NotIn predicate on the "ticket_uuid" field.
func TicketUUIDNotIn(vs ...uuid.UUID) predicate.ThreadModel {
	return predicate.ThreadModel(sql.FieldNotIn(FieldTicketUUID, vs...))
}

// TicketUUIDGT applies the GT predicate on the "ticket_uuid" field.
func TicketUUIDGT(v uuid.UUID) predicate.ThreadModel {
	return predicate.ThreadModel(sql.FieldGT(FieldTicketUUID, v))
}

// TicketUUIDGTE applies the GTE predicate on the "ticket_uuid" field.
func TicketUUIDGTE(v uuid.UUID) predicate.ThreadModel {
	return predicate.ThreadModel(sql.FieldGTE(FieldTicketUUID, v))
}

// TicketUUIDLT applies the LT predicate on the "ticket_uuid" field.
func TicketUUIDLT(v uuid.UUID) predicate.ThreadModel {
	return predicate.ThreadModel(sql.FieldLT(FieldTicketUUID, v))
}

// TicketUUIDLTE applies the LTE predicate on the "ticket_uuid" field.
func TicketUUIDLTE(v uuid.UUID) predicate.ThreadModel {
	return predicate.ThreadModel(sql.FieldLTE(FieldTicketUUID, v))
}

// SourceEQ applies the EQ predicate on the "source" field.
func SourceEQ(v string) predicate.ThreadModel {
	return predicate.ThreadModel(sql.FieldEQ(FieldSource, v))
}

// SourceNEQ applies the NEQ predicate on the "source" field.
func SourceNEQ(v string) predicate.ThreadModel {
	return predicate.ThreadModel(sql.FieldNEQ(FieldSource, v))
}

// SourceIn applies the In predicate on the "source" field.
func SourceIn(vs ...string) predicate.ThreadModel {
	return predicate.ThreadModel(sql.FieldIn(FieldSource, vs...))
}

// SourceNotIn applies the NotIn predicate on the "source" field.
func SourceNotIn(vs ...string) predicate.ThreadModel {
	return predicate.ThreadModel(sql.FieldNotIn(FieldSource, vs...))
}

// SourceGT applies the GT predicate on the "source" field.
func SourceGT(v string) predicate.ThreadModel {
	return predicate.ThreadModel(sql.FieldGT(FieldSource, v))
}

// SourceGTE applies the GTE predicate on the "source" field.
func SourceGTE(v string) predicate.ThreadModel {
	return predicate.ThreadModel(sql.FieldGTE(FieldSource, v))
}

// SourceLT applies the LT predicate on the "source" field.
func SourceLT(v string) predicate.ThreadModel {
	return predicate.ThreadModel(sql.FieldLT(FieldSource, v))
}

// SourceLTE applies the LTE predicate on the "source" field.
func SourceLTE(v string) predicate.ThreadModel {
	return predicate.ThreadModel(sql.FieldLTE(FieldSource, v))
}

// SourceContains applies the Contains predicate on the "source" field.
func SourceContains(v string) predicate.ThreadModel {
	return predicate.ThreadModel(sql.FieldContains(FieldSource, v))
}

// SourceHasPrefix applies the HasPrefix predicate on the "source" field.
func SourceHasPrefix(v string) predicate.ThreadModel {
	return predicate.ThreadModel(sql.FieldHasPrefix(FieldSource, v))
}

// SourceHasSuffix applies the HasSuffix predicate on the "source" field.
func SourceHasSuffix(v string) predicate.ThreadModel {
	return predicate.ThreadModel(sql.FieldHasSuffix(FieldSource, v))
}

// SourceEqualFold applies the EqualFold predicate on the "source" field.
func SourceEqualFold(v string) predicate.ThreadModel {
	return predicate.ThreadModel(sql.FieldEqualFold(FieldSource, v))
}

// SourceContainsFold applies the ContainsFold predicate on the "source" field.
func SourceContainsFold(v string) predicate.ThreadModel {
	return predicate.ThreadModel(sql.FieldContainsFold(FieldSource, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ThreadModel) predicate.ThreadModel {
	return predicate.ThreadModel(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for _, p := range predicates {
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ThreadModel) predicate.ThreadModel {
	return predicate.ThreadModel(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for i, p := range predicates {
			if i > 0 {
				s1.Or()
			}
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ThreadModel) predicate.ThreadModel {
	return predicate.ThreadModel(func(s *sql.Selector) {
		p(s.Not())
	})
}
