// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"kapt/kapt/gql/ent/attachmentmodel"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// AttachmentModelCreate is the builder for creating a AttachmentModel entity.
type AttachmentModelCreate struct {
	config
	mutation *AttachmentModelMutation
	hooks    []Hook
}

// SetLink sets the "link" field.
func (amc *AttachmentModelCreate) SetLink(s string) *AttachmentModelCreate {
	amc.mutation.SetLink(s)
	return amc
}

// SetTicketID sets the "ticket_id" field.
func (amc *AttachmentModelCreate) SetTicketID(u uuid.UUID) *AttachmentModelCreate {
	amc.mutation.SetTicketID(u)
	return amc
}

// SetID sets the "id" field.
func (amc *AttachmentModelCreate) SetID(u uuid.UUID) *AttachmentModelCreate {
	amc.mutation.SetID(u)
	return amc
}

// Mutation returns the AttachmentModelMutation object of the builder.
func (amc *AttachmentModelCreate) Mutation() *AttachmentModelMutation {
	return amc.mutation
}

// Save creates the AttachmentModel in the database.
func (amc *AttachmentModelCreate) Save(ctx context.Context) (*AttachmentModel, error) {
	return withHooks(ctx, amc.sqlSave, amc.mutation, amc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (amc *AttachmentModelCreate) SaveX(ctx context.Context) *AttachmentModel {
	v, err := amc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (amc *AttachmentModelCreate) Exec(ctx context.Context) error {
	_, err := amc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (amc *AttachmentModelCreate) ExecX(ctx context.Context) {
	if err := amc.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (amc *AttachmentModelCreate) check() error {
	if _, ok := amc.mutation.Link(); !ok {
		return &ValidationError{Name: "link", err: errors.New(`ent: missing required field "AttachmentModel.link"`)}
	}
	if _, ok := amc.mutation.TicketID(); !ok {
		return &ValidationError{Name: "ticket_id", err: errors.New(`ent: missing required field "AttachmentModel.ticket_id"`)}
	}
	return nil
}

func (amc *AttachmentModelCreate) sqlSave(ctx context.Context) (*AttachmentModel, error) {
	if err := amc.check(); err != nil {
		return nil, err
	}
	_node, _spec := amc.createSpec()
	if err := sqlgraph.CreateNode(ctx, amc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	amc.mutation.id = &_node.ID
	amc.mutation.done = true
	return _node, nil
}

func (amc *AttachmentModelCreate) createSpec() (*AttachmentModel, *sqlgraph.CreateSpec) {
	var (
		_node = &AttachmentModel{config: amc.config}
		_spec = sqlgraph.NewCreateSpec(attachmentmodel.Table, sqlgraph.NewFieldSpec(attachmentmodel.FieldID, field.TypeUUID))
	)
	if id, ok := amc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := amc.mutation.Link(); ok {
		_spec.SetField(attachmentmodel.FieldLink, field.TypeString, value)
		_node.Link = value
	}
	if value, ok := amc.mutation.TicketID(); ok {
		_spec.SetField(attachmentmodel.FieldTicketID, field.TypeUUID, value)
		_node.TicketID = value
	}
	return _node, _spec
}

// AttachmentModelCreateBulk is the builder for creating many AttachmentModel entities in bulk.
type AttachmentModelCreateBulk struct {
	config
	builders []*AttachmentModelCreate
}

// Save creates the AttachmentModel entities in the database.
func (amcb *AttachmentModelCreateBulk) Save(ctx context.Context) ([]*AttachmentModel, error) {
	specs := make([]*sqlgraph.CreateSpec, len(amcb.builders))
	nodes := make([]*AttachmentModel, len(amcb.builders))
	mutators := make([]Mutator, len(amcb.builders))
	for i := range amcb.builders {
		func(i int, root context.Context) {
			builder := amcb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*AttachmentModelMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, amcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, amcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, amcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (amcb *AttachmentModelCreateBulk) SaveX(ctx context.Context) []*AttachmentModel {
	v, err := amcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (amcb *AttachmentModelCreateBulk) Exec(ctx context.Context) error {
	_, err := amcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (amcb *AttachmentModelCreateBulk) ExecX(ctx context.Context) {
	if err := amcb.Exec(ctx); err != nil {
		panic(err)
	}
}
