// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"kapt/kapt/gql/ent/attachmentmodel"
	"kapt/kapt/gql/ent/predicate"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// AttachmentModelQuery is the builder for querying AttachmentModel entities.
type AttachmentModelQuery struct {
	config
	ctx        *QueryContext
	order      []attachmentmodel.OrderOption
	inters     []Interceptor
	predicates []predicate.AttachmentModel
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the AttachmentModelQuery builder.
func (amq *AttachmentModelQuery) Where(ps ...predicate.AttachmentModel) *AttachmentModelQuery {
	amq.predicates = append(amq.predicates, ps...)
	return amq
}

// Limit the number of records to be returned by this query.
func (amq *AttachmentModelQuery) Limit(limit int) *AttachmentModelQuery {
	amq.ctx.Limit = &limit
	return amq
}

// Offset to start from.
func (amq *AttachmentModelQuery) Offset(offset int) *AttachmentModelQuery {
	amq.ctx.Offset = &offset
	return amq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (amq *AttachmentModelQuery) Unique(unique bool) *AttachmentModelQuery {
	amq.ctx.Unique = &unique
	return amq
}

// Order specifies how the records should be ordered.
func (amq *AttachmentModelQuery) Order(o ...attachmentmodel.OrderOption) *AttachmentModelQuery {
	amq.order = append(amq.order, o...)
	return amq
}

// First returns the first AttachmentModel entity from the query.
// Returns a *NotFoundError when no AttachmentModel was found.
func (amq *AttachmentModelQuery) First(ctx context.Context) (*AttachmentModel, error) {
	nodes, err := amq.Limit(1).All(setContextOp(ctx, amq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{attachmentmodel.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (amq *AttachmentModelQuery) FirstX(ctx context.Context) *AttachmentModel {
	node, err := amq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first AttachmentModel ID from the query.
// Returns a *NotFoundError when no AttachmentModel ID was found.
func (amq *AttachmentModelQuery) FirstID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = amq.Limit(1).IDs(setContextOp(ctx, amq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{attachmentmodel.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (amq *AttachmentModelQuery) FirstIDX(ctx context.Context) uuid.UUID {
	id, err := amq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single AttachmentModel entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one AttachmentModel entity is found.
// Returns a *NotFoundError when no AttachmentModel entities are found.
func (amq *AttachmentModelQuery) Only(ctx context.Context) (*AttachmentModel, error) {
	nodes, err := amq.Limit(2).All(setContextOp(ctx, amq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{attachmentmodel.Label}
	default:
		return nil, &NotSingularError{attachmentmodel.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (amq *AttachmentModelQuery) OnlyX(ctx context.Context) *AttachmentModel {
	node, err := amq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only AttachmentModel ID in the query.
// Returns a *NotSingularError when more than one AttachmentModel ID is found.
// Returns a *NotFoundError when no entities are found.
func (amq *AttachmentModelQuery) OnlyID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = amq.Limit(2).IDs(setContextOp(ctx, amq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{attachmentmodel.Label}
	default:
		err = &NotSingularError{attachmentmodel.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (amq *AttachmentModelQuery) OnlyIDX(ctx context.Context) uuid.UUID {
	id, err := amq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of AttachmentModels.
func (amq *AttachmentModelQuery) All(ctx context.Context) ([]*AttachmentModel, error) {
	ctx = setContextOp(ctx, amq.ctx, "All")
	if err := amq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*AttachmentModel, *AttachmentModelQuery]()
	return withInterceptors[[]*AttachmentModel](ctx, amq, qr, amq.inters)
}

// AllX is like All, but panics if an error occurs.
func (amq *AttachmentModelQuery) AllX(ctx context.Context) []*AttachmentModel {
	nodes, err := amq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of AttachmentModel IDs.
func (amq *AttachmentModelQuery) IDs(ctx context.Context) (ids []uuid.UUID, err error) {
	if amq.ctx.Unique == nil && amq.path != nil {
		amq.Unique(true)
	}
	ctx = setContextOp(ctx, amq.ctx, "IDs")
	if err = amq.Select(attachmentmodel.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (amq *AttachmentModelQuery) IDsX(ctx context.Context) []uuid.UUID {
	ids, err := amq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (amq *AttachmentModelQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, amq.ctx, "Count")
	if err := amq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, amq, querierCount[*AttachmentModelQuery](), amq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (amq *AttachmentModelQuery) CountX(ctx context.Context) int {
	count, err := amq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (amq *AttachmentModelQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, amq.ctx, "Exist")
	switch _, err := amq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (amq *AttachmentModelQuery) ExistX(ctx context.Context) bool {
	exist, err := amq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the AttachmentModelQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (amq *AttachmentModelQuery) Clone() *AttachmentModelQuery {
	if amq == nil {
		return nil
	}
	return &AttachmentModelQuery{
		config:     amq.config,
		ctx:        amq.ctx.Clone(),
		order:      append([]attachmentmodel.OrderOption{}, amq.order...),
		inters:     append([]Interceptor{}, amq.inters...),
		predicates: append([]predicate.AttachmentModel{}, amq.predicates...),
		// clone intermediate query.
		sql:  amq.sql.Clone(),
		path: amq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Link string `json:"link,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.AttachmentModel.Query().
//		GroupBy(attachmentmodel.FieldLink).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (amq *AttachmentModelQuery) GroupBy(field string, fields ...string) *AttachmentModelGroupBy {
	amq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &AttachmentModelGroupBy{build: amq}
	grbuild.flds = &amq.ctx.Fields
	grbuild.label = attachmentmodel.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Link string `json:"link,omitempty"`
//	}
//
//	client.AttachmentModel.Query().
//		Select(attachmentmodel.FieldLink).
//		Scan(ctx, &v)
func (amq *AttachmentModelQuery) Select(fields ...string) *AttachmentModelSelect {
	amq.ctx.Fields = append(amq.ctx.Fields, fields...)
	sbuild := &AttachmentModelSelect{AttachmentModelQuery: amq}
	sbuild.label = attachmentmodel.Label
	sbuild.flds, sbuild.scan = &amq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a AttachmentModelSelect configured with the given aggregations.
func (amq *AttachmentModelQuery) Aggregate(fns ...AggregateFunc) *AttachmentModelSelect {
	return amq.Select().Aggregate(fns...)
}

func (amq *AttachmentModelQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range amq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, amq); err != nil {
				return err
			}
		}
	}
	for _, f := range amq.ctx.Fields {
		if !attachmentmodel.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if amq.path != nil {
		prev, err := amq.path(ctx)
		if err != nil {
			return err
		}
		amq.sql = prev
	}
	return nil
}

func (amq *AttachmentModelQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*AttachmentModel, error) {
	var (
		nodes = []*AttachmentModel{}
		_spec = amq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*AttachmentModel).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &AttachmentModel{config: amq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, amq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (amq *AttachmentModelQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := amq.querySpec()
	_spec.Node.Columns = amq.ctx.Fields
	if len(amq.ctx.Fields) > 0 {
		_spec.Unique = amq.ctx.Unique != nil && *amq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, amq.driver, _spec)
}

func (amq *AttachmentModelQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(attachmentmodel.Table, attachmentmodel.Columns, sqlgraph.NewFieldSpec(attachmentmodel.FieldID, field.TypeUUID))
	_spec.From = amq.sql
	if unique := amq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if amq.path != nil {
		_spec.Unique = true
	}
	if fields := amq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, attachmentmodel.FieldID)
		for i := range fields {
			if fields[i] != attachmentmodel.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := amq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := amq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := amq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := amq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (amq *AttachmentModelQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(amq.driver.Dialect())
	t1 := builder.Table(attachmentmodel.Table)
	columns := amq.ctx.Fields
	if len(columns) == 0 {
		columns = attachmentmodel.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if amq.sql != nil {
		selector = amq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if amq.ctx.Unique != nil && *amq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range amq.predicates {
		p(selector)
	}
	for _, p := range amq.order {
		p(selector)
	}
	if offset := amq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := amq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// AttachmentModelGroupBy is the group-by builder for AttachmentModel entities.
type AttachmentModelGroupBy struct {
	selector
	build *AttachmentModelQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (amgb *AttachmentModelGroupBy) Aggregate(fns ...AggregateFunc) *AttachmentModelGroupBy {
	amgb.fns = append(amgb.fns, fns...)
	return amgb
}

// Scan applies the selector query and scans the result into the given value.
func (amgb *AttachmentModelGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, amgb.build.ctx, "GroupBy")
	if err := amgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*AttachmentModelQuery, *AttachmentModelGroupBy](ctx, amgb.build, amgb, amgb.build.inters, v)
}

func (amgb *AttachmentModelGroupBy) sqlScan(ctx context.Context, root *AttachmentModelQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(amgb.fns))
	for _, fn := range amgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*amgb.flds)+len(amgb.fns))
		for _, f := range *amgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*amgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := amgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// AttachmentModelSelect is the builder for selecting fields of AttachmentModel entities.
type AttachmentModelSelect struct {
	*AttachmentModelQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (ams *AttachmentModelSelect) Aggregate(fns ...AggregateFunc) *AttachmentModelSelect {
	ams.fns = append(ams.fns, fns...)
	return ams
}

// Scan applies the selector query and scans the result into the given value.
func (ams *AttachmentModelSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, ams.ctx, "Select")
	if err := ams.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*AttachmentModelQuery, *AttachmentModelSelect](ctx, ams.AttachmentModelQuery, ams, ams.inters, v)
}

func (ams *AttachmentModelSelect) sqlScan(ctx context.Context, root *AttachmentModelQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(ams.fns))
	for _, fn := range ams.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*ams.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := ams.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
