// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"kapt/kapt/gql/ent/tenantmodel"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

// TenantModel is the model entity for the TenantModel schema.
type TenantModel struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// TenantName holds the value of the "tenant_name" field.
	TenantName string `json:"tenant_name,omitempty"`
	// Status holds the value of the "status" field.
	Status       int `json:"status,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*TenantModel) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case tenantmodel.FieldStatus:
			values[i] = new(sql.NullInt64)
		case tenantmodel.FieldTenantName:
			values[i] = new(sql.NullString)
		case tenantmodel.FieldID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the TenantModel fields.
func (tm *TenantModel) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case tenantmodel.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				tm.ID = *value
			}
		case tenantmodel.FieldTenantName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field tenant_name", values[i])
			} else if value.Valid {
				tm.TenantName = value.String
			}
		case tenantmodel.FieldStatus:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				tm.Status = int(value.Int64)
			}
		default:
			tm.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the TenantModel.
// This includes values selected through modifiers, order, etc.
func (tm *TenantModel) Value(name string) (ent.Value, error) {
	return tm.selectValues.Get(name)
}

// Update returns a builder for updating this TenantModel.
// Note that you need to call TenantModel.Unwrap() before calling this method if this TenantModel
// was returned from a transaction, and the transaction was committed or rolled back.
func (tm *TenantModel) Update() *TenantModelUpdateOne {
	return NewTenantModelClient(tm.config).UpdateOne(tm)
}

// Unwrap unwraps the TenantModel entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (tm *TenantModel) Unwrap() *TenantModel {
	_tx, ok := tm.config.driver.(*txDriver)
	if !ok {
		panic("ent: TenantModel is not a transactional entity")
	}
	tm.config.driver = _tx.drv
	return tm
}

// String implements the fmt.Stringer.
func (tm *TenantModel) String() string {
	var builder strings.Builder
	builder.WriteString("TenantModel(")
	builder.WriteString(fmt.Sprintf("id=%v, ", tm.ID))
	builder.WriteString("tenant_name=")
	builder.WriteString(tm.TenantName)
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(fmt.Sprintf("%v", tm.Status))
	builder.WriteByte(')')
	return builder.String()
}

// TenantModels is a parsable slice of TenantModel.
type TenantModels []*TenantModel
