// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"kapt/kapt/gql/ent/predicate"
	"kapt/kapt/gql/ent/tenantmodel"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// TenantModelDelete is the builder for deleting a TenantModel entity.
type TenantModelDelete struct {
	config
	hooks    []Hook
	mutation *TenantModelMutation
}

// Where appends a list predicates to the TenantModelDelete builder.
func (tmd *TenantModelDelete) Where(ps ...predicate.TenantModel) *TenantModelDelete {
	tmd.mutation.Where(ps...)
	return tmd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (tmd *TenantModelDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, tmd.sqlExec, tmd.mutation, tmd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (tmd *TenantModelDelete) ExecX(ctx context.Context) int {
	n, err := tmd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (tmd *TenantModelDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(tenantmodel.Table, sqlgraph.NewFieldSpec(tenantmodel.FieldID, field.TypeUUID))
	if ps := tmd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, tmd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	tmd.mutation.done = true
	return affected, err
}

// TenantModelDeleteOne is the builder for deleting a single TenantModel entity.
type TenantModelDeleteOne struct {
	tmd *TenantModelDelete
}

// Where appends a list predicates to the TenantModelDelete builder.
func (tmdo *TenantModelDeleteOne) Where(ps ...predicate.TenantModel) *TenantModelDeleteOne {
	tmdo.tmd.mutation.Where(ps...)
	return tmdo
}

// Exec executes the deletion query.
func (tmdo *TenantModelDeleteOne) Exec(ctx context.Context) error {
	n, err := tmdo.tmd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{tenantmodel.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (tmdo *TenantModelDeleteOne) ExecX(ctx context.Context) {
	if err := tmdo.Exec(ctx); err != nil {
		panic(err)
	}
}
