// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"kapt/kapt/gql/ent/predicate"
	"kapt/kapt/gql/ent/tenantmodel"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// TenantModelQuery is the builder for querying TenantModel entities.
type TenantModelQuery struct {
	config
	ctx        *QueryContext
	order      []tenantmodel.OrderOption
	inters     []Interceptor
	predicates []predicate.TenantModel
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the TenantModelQuery builder.
func (tmq *TenantModelQuery) Where(ps ...predicate.TenantModel) *TenantModelQuery {
	tmq.predicates = append(tmq.predicates, ps...)
	return tmq
}

// Limit the number of records to be returned by this query.
func (tmq *TenantModelQuery) Limit(limit int) *TenantModelQuery {
	tmq.ctx.Limit = &limit
	return tmq
}

// Offset to start from.
func (tmq *TenantModelQuery) Offset(offset int) *TenantModelQuery {
	tmq.ctx.Offset = &offset
	return tmq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (tmq *TenantModelQuery) Unique(unique bool) *TenantModelQuery {
	tmq.ctx.Unique = &unique
	return tmq
}

// Order specifies how the records should be ordered.
func (tmq *TenantModelQuery) Order(o ...tenantmodel.OrderOption) *TenantModelQuery {
	tmq.order = append(tmq.order, o...)
	return tmq
}

// First returns the first TenantModel entity from the query.
// Returns a *NotFoundError when no TenantModel was found.
func (tmq *TenantModelQuery) First(ctx context.Context) (*TenantModel, error) {
	nodes, err := tmq.Limit(1).All(setContextOp(ctx, tmq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{tenantmodel.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (tmq *TenantModelQuery) FirstX(ctx context.Context) *TenantModel {
	node, err := tmq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first TenantModel ID from the query.
// Returns a *NotFoundError when no TenantModel ID was found.
func (tmq *TenantModelQuery) FirstID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = tmq.Limit(1).IDs(setContextOp(ctx, tmq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{tenantmodel.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (tmq *TenantModelQuery) FirstIDX(ctx context.Context) uuid.UUID {
	id, err := tmq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single TenantModel entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one TenantModel entity is found.
// Returns a *NotFoundError when no TenantModel entities are found.
func (tmq *TenantModelQuery) Only(ctx context.Context) (*TenantModel, error) {
	nodes, err := tmq.Limit(2).All(setContextOp(ctx, tmq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{tenantmodel.Label}
	default:
		return nil, &NotSingularError{tenantmodel.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (tmq *TenantModelQuery) OnlyX(ctx context.Context) *TenantModel {
	node, err := tmq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only TenantModel ID in the query.
// Returns a *NotSingularError when more than one TenantModel ID is found.
// Returns a *NotFoundError when no entities are found.
func (tmq *TenantModelQuery) OnlyID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = tmq.Limit(2).IDs(setContextOp(ctx, tmq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{tenantmodel.Label}
	default:
		err = &NotSingularError{tenantmodel.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (tmq *TenantModelQuery) OnlyIDX(ctx context.Context) uuid.UUID {
	id, err := tmq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of TenantModels.
func (tmq *TenantModelQuery) All(ctx context.Context) ([]*TenantModel, error) {
	ctx = setContextOp(ctx, tmq.ctx, "All")
	if err := tmq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*TenantModel, *TenantModelQuery]()
	return withInterceptors[[]*TenantModel](ctx, tmq, qr, tmq.inters)
}

// AllX is like All, but panics if an error occurs.
func (tmq *TenantModelQuery) AllX(ctx context.Context) []*TenantModel {
	nodes, err := tmq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of TenantModel IDs.
func (tmq *TenantModelQuery) IDs(ctx context.Context) (ids []uuid.UUID, err error) {
	if tmq.ctx.Unique == nil && tmq.path != nil {
		tmq.Unique(true)
	}
	ctx = setContextOp(ctx, tmq.ctx, "IDs")
	if err = tmq.Select(tenantmodel.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (tmq *TenantModelQuery) IDsX(ctx context.Context) []uuid.UUID {
	ids, err := tmq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (tmq *TenantModelQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, tmq.ctx, "Count")
	if err := tmq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, tmq, querierCount[*TenantModelQuery](), tmq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (tmq *TenantModelQuery) CountX(ctx context.Context) int {
	count, err := tmq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (tmq *TenantModelQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, tmq.ctx, "Exist")
	switch _, err := tmq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (tmq *TenantModelQuery) ExistX(ctx context.Context) bool {
	exist, err := tmq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the TenantModelQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (tmq *TenantModelQuery) Clone() *TenantModelQuery {
	if tmq == nil {
		return nil
	}
	return &TenantModelQuery{
		config:     tmq.config,
		ctx:        tmq.ctx.Clone(),
		order:      append([]tenantmodel.OrderOption{}, tmq.order...),
		inters:     append([]Interceptor{}, tmq.inters...),
		predicates: append([]predicate.TenantModel{}, tmq.predicates...),
		// clone intermediate query.
		sql:  tmq.sql.Clone(),
		path: tmq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		TenantName string `json:"tenant_name,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.TenantModel.Query().
//		GroupBy(tenantmodel.FieldTenantName).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (tmq *TenantModelQuery) GroupBy(field string, fields ...string) *TenantModelGroupBy {
	tmq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &TenantModelGroupBy{build: tmq}
	grbuild.flds = &tmq.ctx.Fields
	grbuild.label = tenantmodel.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		TenantName string `json:"tenant_name,omitempty"`
//	}
//
//	client.TenantModel.Query().
//		Select(tenantmodel.FieldTenantName).
//		Scan(ctx, &v)
func (tmq *TenantModelQuery) Select(fields ...string) *TenantModelSelect {
	tmq.ctx.Fields = append(tmq.ctx.Fields, fields...)
	sbuild := &TenantModelSelect{TenantModelQuery: tmq}
	sbuild.label = tenantmodel.Label
	sbuild.flds, sbuild.scan = &tmq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a TenantModelSelect configured with the given aggregations.
func (tmq *TenantModelQuery) Aggregate(fns ...AggregateFunc) *TenantModelSelect {
	return tmq.Select().Aggregate(fns...)
}

func (tmq *TenantModelQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range tmq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, tmq); err != nil {
				return err
			}
		}
	}
	for _, f := range tmq.ctx.Fields {
		if !tenantmodel.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if tmq.path != nil {
		prev, err := tmq.path(ctx)
		if err != nil {
			return err
		}
		tmq.sql = prev
	}
	return nil
}

func (tmq *TenantModelQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*TenantModel, error) {
	var (
		nodes = []*TenantModel{}
		_spec = tmq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*TenantModel).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &TenantModel{config: tmq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, tmq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (tmq *TenantModelQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := tmq.querySpec()
	_spec.Node.Columns = tmq.ctx.Fields
	if len(tmq.ctx.Fields) > 0 {
		_spec.Unique = tmq.ctx.Unique != nil && *tmq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, tmq.driver, _spec)
}

func (tmq *TenantModelQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(tenantmodel.Table, tenantmodel.Columns, sqlgraph.NewFieldSpec(tenantmodel.FieldID, field.TypeUUID))
	_spec.From = tmq.sql
	if unique := tmq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if tmq.path != nil {
		_spec.Unique = true
	}
	if fields := tmq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, tenantmodel.FieldID)
		for i := range fields {
			if fields[i] != tenantmodel.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := tmq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := tmq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := tmq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := tmq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (tmq *TenantModelQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(tmq.driver.Dialect())
	t1 := builder.Table(tenantmodel.Table)
	columns := tmq.ctx.Fields
	if len(columns) == 0 {
		columns = tenantmodel.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if tmq.sql != nil {
		selector = tmq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if tmq.ctx.Unique != nil && *tmq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range tmq.predicates {
		p(selector)
	}
	for _, p := range tmq.order {
		p(selector)
	}
	if offset := tmq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := tmq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// TenantModelGroupBy is the group-by builder for TenantModel entities.
type TenantModelGroupBy struct {
	selector
	build *TenantModelQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (tmgb *TenantModelGroupBy) Aggregate(fns ...AggregateFunc) *TenantModelGroupBy {
	tmgb.fns = append(tmgb.fns, fns...)
	return tmgb
}

// Scan applies the selector query and scans the result into the given value.
func (tmgb *TenantModelGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, tmgb.build.ctx, "GroupBy")
	if err := tmgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*TenantModelQuery, *TenantModelGroupBy](ctx, tmgb.build, tmgb, tmgb.build.inters, v)
}

func (tmgb *TenantModelGroupBy) sqlScan(ctx context.Context, root *TenantModelQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(tmgb.fns))
	for _, fn := range tmgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*tmgb.flds)+len(tmgb.fns))
		for _, f := range *tmgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*tmgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := tmgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// TenantModelSelect is the builder for selecting fields of TenantModel entities.
type TenantModelSelect struct {
	*TenantModelQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (tms *TenantModelSelect) Aggregate(fns ...AggregateFunc) *TenantModelSelect {
	tms.fns = append(tms.fns, fns...)
	return tms
}

// Scan applies the selector query and scans the result into the given value.
func (tms *TenantModelSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, tms.ctx, "Select")
	if err := tms.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*TenantModelQuery, *TenantModelSelect](ctx, tms.TenantModelQuery, tms, tms.inters, v)
}

func (tms *TenantModelSelect) sqlScan(ctx context.Context, root *TenantModelQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(tms.fns))
	for _, fn := range tms.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*tms.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := tms.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
