// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"kapt/kapt/gql/ent/predicate"
	"kapt/kapt/gql/ent/threadmodel"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// ThreadModelUpdate is the builder for updating ThreadModel entities.
type ThreadModelUpdate struct {
	config
	hooks    []Hook
	mutation *ThreadModelMutation
}

// Where appends a list predicates to the ThreadModelUpdate builder.
func (tmu *ThreadModelUpdate) Where(ps ...predicate.ThreadModel) *ThreadModelUpdate {
	tmu.mutation.Where(ps...)
	return tmu
}

// SetBody sets the "body" field.
func (tmu *ThreadModelUpdate) SetBody(s string) *ThreadModelUpdate {
	tmu.mutation.SetBody(s)
	return tmu
}

// SetTime sets the "time" field.
func (tmu *ThreadModelUpdate) SetTime(t time.Time) *ThreadModelUpdate {
	tmu.mutation.SetTime(t)
	return tmu
}

// SetTicketUUID sets the "ticket_uuid" field.
func (tmu *ThreadModelUpdate) SetTicketUUID(u uuid.UUID) *ThreadModelUpdate {
	tmu.mutation.SetTicketUUID(u)
	return tmu
}

// SetSource sets the "source" field.
func (tmu *ThreadModelUpdate) SetSource(s string) *ThreadModelUpdate {
	tmu.mutation.SetSource(s)
	return tmu
}

// Mutation returns the ThreadModelMutation object of the builder.
func (tmu *ThreadModelUpdate) Mutation() *ThreadModelMutation {
	return tmu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (tmu *ThreadModelUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, tmu.sqlSave, tmu.mutation, tmu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (tmu *ThreadModelUpdate) SaveX(ctx context.Context) int {
	affected, err := tmu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (tmu *ThreadModelUpdate) Exec(ctx context.Context) error {
	_, err := tmu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (tmu *ThreadModelUpdate) ExecX(ctx context.Context) {
	if err := tmu.Exec(ctx); err != nil {
		panic(err)
	}
}

func (tmu *ThreadModelUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := sqlgraph.NewUpdateSpec(threadmodel.Table, threadmodel.Columns, sqlgraph.NewFieldSpec(threadmodel.FieldID, field.TypeUUID))
	if ps := tmu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := tmu.mutation.Body(); ok {
		_spec.SetField(threadmodel.FieldBody, field.TypeString, value)
	}
	if value, ok := tmu.mutation.Time(); ok {
		_spec.SetField(threadmodel.FieldTime, field.TypeTime, value)
	}
	if value, ok := tmu.mutation.TicketUUID(); ok {
		_spec.SetField(threadmodel.FieldTicketUUID, field.TypeUUID, value)
	}
	if value, ok := tmu.mutation.Source(); ok {
		_spec.SetField(threadmodel.FieldSource, field.TypeString, value)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, tmu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{threadmodel.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	tmu.mutation.done = true
	return n, nil
}

// ThreadModelUpdateOne is the builder for updating a single ThreadModel entity.
type ThreadModelUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ThreadModelMutation
}

// SetBody sets the "body" field.
func (tmuo *ThreadModelUpdateOne) SetBody(s string) *ThreadModelUpdateOne {
	tmuo.mutation.SetBody(s)
	return tmuo
}

// SetTime sets the "time" field.
func (tmuo *ThreadModelUpdateOne) SetTime(t time.Time) *ThreadModelUpdateOne {
	tmuo.mutation.SetTime(t)
	return tmuo
}

// SetTicketUUID sets the "ticket_uuid" field.
func (tmuo *ThreadModelUpdateOne) SetTicketUUID(u uuid.UUID) *ThreadModelUpdateOne {
	tmuo.mutation.SetTicketUUID(u)
	return tmuo
}

// SetSource sets the "source" field.
func (tmuo *ThreadModelUpdateOne) SetSource(s string) *ThreadModelUpdateOne {
	tmuo.mutation.SetSource(s)
	return tmuo
}

// Mutation returns the ThreadModelMutation object of the builder.
func (tmuo *ThreadModelUpdateOne) Mutation() *ThreadModelMutation {
	return tmuo.mutation
}

// Where appends a list predicates to the ThreadModelUpdate builder.
func (tmuo *ThreadModelUpdateOne) Where(ps ...predicate.ThreadModel) *ThreadModelUpdateOne {
	tmuo.mutation.Where(ps...)
	return tmuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (tmuo *ThreadModelUpdateOne) Select(field string, fields ...string) *ThreadModelUpdateOne {
	tmuo.fields = append([]string{field}, fields...)
	return tmuo
}

// Save executes the query and returns the updated ThreadModel entity.
func (tmuo *ThreadModelUpdateOne) Save(ctx context.Context) (*ThreadModel, error) {
	return withHooks(ctx, tmuo.sqlSave, tmuo.mutation, tmuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (tmuo *ThreadModelUpdateOne) SaveX(ctx context.Context) *ThreadModel {
	node, err := tmuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (tmuo *ThreadModelUpdateOne) Exec(ctx context.Context) error {
	_, err := tmuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (tmuo *ThreadModelUpdateOne) ExecX(ctx context.Context) {
	if err := tmuo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (tmuo *ThreadModelUpdateOne) sqlSave(ctx context.Context) (_node *ThreadModel, err error) {
	_spec := sqlgraph.NewUpdateSpec(threadmodel.Table, threadmodel.Columns, sqlgraph.NewFieldSpec(threadmodel.FieldID, field.TypeUUID))
	id, ok := tmuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ThreadModel.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := tmuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, threadmodel.FieldID)
		for _, f := range fields {
			if !threadmodel.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != threadmodel.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := tmuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := tmuo.mutation.Body(); ok {
		_spec.SetField(threadmodel.FieldBody, field.TypeString, value)
	}
	if value, ok := tmuo.mutation.Time(); ok {
		_spec.SetField(threadmodel.FieldTime, field.TypeTime, value)
	}
	if value, ok := tmuo.mutation.TicketUUID(); ok {
		_spec.SetField(threadmodel.FieldTicketUUID, field.TypeUUID, value)
	}
	if value, ok := tmuo.mutation.Source(); ok {
		_spec.SetField(threadmodel.FieldSource, field.TypeString, value)
	}
	_node = &ThreadModel{config: tmuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, tmuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{threadmodel.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	tmuo.mutation.done = true
	return _node, nil
}
