// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"kapt/kapt/gql/ent/predicate"
	"kapt/kapt/gql/ent/threadmodel"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ThreadModelDelete is the builder for deleting a ThreadModel entity.
type ThreadModelDelete struct {
	config
	hooks    []Hook
	mutation *ThreadModelMutation
}

// Where appends a list predicates to the ThreadModelDelete builder.
func (tmd *ThreadModelDelete) Where(ps ...predicate.ThreadModel) *ThreadModelDelete {
	tmd.mutation.Where(ps...)
	return tmd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (tmd *ThreadModelDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, tmd.sqlExec, tmd.mutation, tmd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (tmd *ThreadModelDelete) ExecX(ctx context.Context) int {
	n, err := tmd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (tmd *ThreadModelDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(threadmodel.Table, sqlgraph.NewFieldSpec(threadmodel.FieldID, field.TypeUUID))
	if ps := tmd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, tmd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	tmd.mutation.done = true
	return affected, err
}

// ThreadModelDeleteOne is the builder for deleting a single ThreadModel entity.
type ThreadModelDeleteOne struct {
	tmd *ThreadModelDelete
}

// Where appends a list predicates to the ThreadModelDelete builder.
func (tmdo *ThreadModelDeleteOne) Where(ps ...predicate.ThreadModel) *ThreadModelDeleteOne {
	tmdo.tmd.mutation.Where(ps...)
	return tmdo
}

// Exec executes the deletion query.
func (tmdo *ThreadModelDeleteOne) Exec(ctx context.Context) error {
	n, err := tmdo.tmd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{threadmodel.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (tmdo *ThreadModelDeleteOne) ExecX(ctx context.Context) {
	if err := tmdo.Exec(ctx); err != nil {
		panic(err)
	}
}
