// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"kapt/kapt/gql/ent/predicate"
	"kapt/kapt/gql/ent/ticketmodel"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// TicketModelUpdate is the builder for updating TicketModel entities.
type TicketModelUpdate struct {
	config
	hooks    []Hook
	mutation *TicketModelMutation
}

// Where appends a list predicates to the TicketModelUpdate builder.
func (tmu *TicketModelUpdate) Where(ps ...predicate.TicketModel) *TicketModelUpdate {
	tmu.mutation.Where(ps...)
	return tmu
}

// SetUserID sets the "user_id" field.
func (tmu *TicketModelUpdate) SetUserID(u uuid.UUID) *TicketModelUpdate {
	tmu.mutation.SetUserID(u)
	return tmu
}

// SetTenantID sets the "tenant_id" field.
func (tmu *TicketModelUpdate) SetTenantID(u uuid.UUID) *TicketModelUpdate {
	tmu.mutation.SetTenantID(u)
	return tmu
}

// SetSubject sets the "subject" field.
func (tmu *TicketModelUpdate) SetSubject(s string) *TicketModelUpdate {
	tmu.mutation.SetSubject(s)
	return tmu
}

// SetBody sets the "body" field.
func (tmu *TicketModelUpdate) SetBody(s string) *TicketModelUpdate {
	tmu.mutation.SetBody(s)
	return tmu
}

// SetCategory sets the "category" field.
func (tmu *TicketModelUpdate) SetCategory(u uuid.UUID) *TicketModelUpdate {
	tmu.mutation.SetCategory(u)
	return tmu
}

// SetLabel sets the "label" field.
func (tmu *TicketModelUpdate) SetLabel(s string) *TicketModelUpdate {
	tmu.mutation.SetLabel(s)
	return tmu
}

// SetAssigneeID sets the "assignee_id" field.
func (tmu *TicketModelUpdate) SetAssigneeID(u uuid.UUID) *TicketModelUpdate {
	tmu.mutation.SetAssigneeID(u)
	return tmu
}

// SetSeverity sets the "severity" field.
func (tmu *TicketModelUpdate) SetSeverity(i int) *TicketModelUpdate {
	tmu.mutation.ResetSeverity()
	tmu.mutation.SetSeverity(i)
	return tmu
}

// AddSeverity adds i to the "severity" field.
func (tmu *TicketModelUpdate) AddSeverity(i int) *TicketModelUpdate {
	tmu.mutation.AddSeverity(i)
	return tmu
}

// SetStatus sets the "status" field.
func (tmu *TicketModelUpdate) SetStatus(i int) *TicketModelUpdate {
	tmu.mutation.ResetStatus()
	tmu.mutation.SetStatus(i)
	return tmu
}

// AddStatus adds i to the "status" field.
func (tmu *TicketModelUpdate) AddStatus(i int) *TicketModelUpdate {
	tmu.mutation.AddStatus(i)
	return tmu
}

// SetTime sets the "time" field.
func (tmu *TicketModelUpdate) SetTime(t time.Time) *TicketModelUpdate {
	tmu.mutation.SetTime(t)
	return tmu
}

// Mutation returns the TicketModelMutation object of the builder.
func (tmu *TicketModelUpdate) Mutation() *TicketModelMutation {
	return tmu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (tmu *TicketModelUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, tmu.sqlSave, tmu.mutation, tmu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (tmu *TicketModelUpdate) SaveX(ctx context.Context) int {
	affected, err := tmu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (tmu *TicketModelUpdate) Exec(ctx context.Context) error {
	_, err := tmu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (tmu *TicketModelUpdate) ExecX(ctx context.Context) {
	if err := tmu.Exec(ctx); err != nil {
		panic(err)
	}
}

func (tmu *TicketModelUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := sqlgraph.NewUpdateSpec(ticketmodel.Table, ticketmodel.Columns, sqlgraph.NewFieldSpec(ticketmodel.FieldID, field.TypeUUID))
	if ps := tmu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := tmu.mutation.UserID(); ok {
		_spec.SetField(ticketmodel.FieldUserID, field.TypeUUID, value)
	}
	if value, ok := tmu.mutation.TenantID(); ok {
		_spec.SetField(ticketmodel.FieldTenantID, field.TypeUUID, value)
	}
	if value, ok := tmu.mutation.Subject(); ok {
		_spec.SetField(ticketmodel.FieldSubject, field.TypeString, value)
	}
	if value, ok := tmu.mutation.Body(); ok {
		_spec.SetField(ticketmodel.FieldBody, field.TypeString, value)
	}
	if value, ok := tmu.mutation.Category(); ok {
		_spec.SetField(ticketmodel.FieldCategory, field.TypeUUID, value)
	}
	if value, ok := tmu.mutation.Label(); ok {
		_spec.SetField(ticketmodel.FieldLabel, field.TypeString, value)
	}
	if value, ok := tmu.mutation.AssigneeID(); ok {
		_spec.SetField(ticketmodel.FieldAssigneeID, field.TypeUUID, value)
	}
	if value, ok := tmu.mutation.Severity(); ok {
		_spec.SetField(ticketmodel.FieldSeverity, field.TypeInt, value)
	}
	if value, ok := tmu.mutation.AddedSeverity(); ok {
		_spec.AddField(ticketmodel.FieldSeverity, field.TypeInt, value)
	}
	if value, ok := tmu.mutation.Status(); ok {
		_spec.SetField(ticketmodel.FieldStatus, field.TypeInt, value)
	}
	if value, ok := tmu.mutation.AddedStatus(); ok {
		_spec.AddField(ticketmodel.FieldStatus, field.TypeInt, value)
	}
	if value, ok := tmu.mutation.Time(); ok {
		_spec.SetField(ticketmodel.FieldTime, field.TypeTime, value)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, tmu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{ticketmodel.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	tmu.mutation.done = true
	return n, nil
}

// TicketModelUpdateOne is the builder for updating a single TicketModel entity.
type TicketModelUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *TicketModelMutation
}

// SetUserID sets the "user_id" field.
func (tmuo *TicketModelUpdateOne) SetUserID(u uuid.UUID) *TicketModelUpdateOne {
	tmuo.mutation.SetUserID(u)
	return tmuo
}

// SetTenantID sets the "tenant_id" field.
func (tmuo *TicketModelUpdateOne) SetTenantID(u uuid.UUID) *TicketModelUpdateOne {
	tmuo.mutation.SetTenantID(u)
	return tmuo
}

// SetSubject sets the "subject" field.
func (tmuo *TicketModelUpdateOne) SetSubject(s string) *TicketModelUpdateOne {
	tmuo.mutation.SetSubject(s)
	return tmuo
}

// SetBody sets the "body" field.
func (tmuo *TicketModelUpdateOne) SetBody(s string) *TicketModelUpdateOne {
	tmuo.mutation.SetBody(s)
	return tmuo
}

// SetCategory sets the "category" field.
func (tmuo *TicketModelUpdateOne) SetCategory(u uuid.UUID) *TicketModelUpdateOne {
	tmuo.mutation.SetCategory(u)
	return tmuo
}

// SetLabel sets the "label" field.
func (tmuo *TicketModelUpdateOne) SetLabel(s string) *TicketModelUpdateOne {
	tmuo.mutation.SetLabel(s)
	return tmuo
}

// SetAssigneeID sets the "assignee_id" field.
func (tmuo *TicketModelUpdateOne) SetAssigneeID(u uuid.UUID) *TicketModelUpdateOne {
	tmuo.mutation.SetAssigneeID(u)
	return tmuo
}

// SetSeverity sets the "severity" field.
func (tmuo *TicketModelUpdateOne) SetSeverity(i int) *TicketModelUpdateOne {
	tmuo.mutation.ResetSeverity()
	tmuo.mutation.SetSeverity(i)
	return tmuo
}

// AddSeverity adds i to the "severity" field.
func (tmuo *TicketModelUpdateOne) AddSeverity(i int) *TicketModelUpdateOne {
	tmuo.mutation.AddSeverity(i)
	return tmuo
}

// SetStatus sets the "status" field.
func (tmuo *TicketModelUpdateOne) SetStatus(i int) *TicketModelUpdateOne {
	tmuo.mutation.ResetStatus()
	tmuo.mutation.SetStatus(i)
	return tmuo
}

// AddStatus adds i to the "status" field.
func (tmuo *TicketModelUpdateOne) AddStatus(i int) *TicketModelUpdateOne {
	tmuo.mutation.AddStatus(i)
	return tmuo
}

// SetTime sets the "time" field.
func (tmuo *TicketModelUpdateOne) SetTime(t time.Time) *TicketModelUpdateOne {
	tmuo.mutation.SetTime(t)
	return tmuo
}

// Mutation returns the TicketModelMutation object of the builder.
func (tmuo *TicketModelUpdateOne) Mutation() *TicketModelMutation {
	return tmuo.mutation
}

// Where appends a list predicates to the TicketModelUpdate builder.
func (tmuo *TicketModelUpdateOne) Where(ps ...predicate.TicketModel) *TicketModelUpdateOne {
	tmuo.mutation.Where(ps...)
	return tmuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (tmuo *TicketModelUpdateOne) Select(field string, fields ...string) *TicketModelUpdateOne {
	tmuo.fields = append([]string{field}, fields...)
	return tmuo
}

// Save executes the query and returns the updated TicketModel entity.
func (tmuo *TicketModelUpdateOne) Save(ctx context.Context) (*TicketModel, error) {
	return withHooks(ctx, tmuo.sqlSave, tmuo.mutation, tmuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (tmuo *TicketModelUpdateOne) SaveX(ctx context.Context) *TicketModel {
	node, err := tmuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (tmuo *TicketModelUpdateOne) Exec(ctx context.Context) error {
	_, err := tmuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (tmuo *TicketModelUpdateOne) ExecX(ctx context.Context) {
	if err := tmuo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (tmuo *TicketModelUpdateOne) sqlSave(ctx context.Context) (_node *TicketModel, err error) {
	_spec := sqlgraph.NewUpdateSpec(ticketmodel.Table, ticketmodel.Columns, sqlgraph.NewFieldSpec(ticketmodel.FieldID, field.TypeUUID))
	id, ok := tmuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "TicketModel.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := tmuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, ticketmodel.FieldID)
		for _, f := range fields {
			if !ticketmodel.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != ticketmodel.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := tmuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := tmuo.mutation.UserID(); ok {
		_spec.SetField(ticketmodel.FieldUserID, field.TypeUUID, value)
	}
	if value, ok := tmuo.mutation.TenantID(); ok {
		_spec.SetField(ticketmodel.FieldTenantID, field.TypeUUID, value)
	}
	if value, ok := tmuo.mutation.Subject(); ok {
		_spec.SetField(ticketmodel.FieldSubject, field.TypeString, value)
	}
	if value, ok := tmuo.mutation.Body(); ok {
		_spec.SetField(ticketmodel.FieldBody, field.TypeString, value)
	}
	if value, ok := tmuo.mutation.Category(); ok {
		_spec.SetField(ticketmodel.FieldCategory, field.TypeUUID, value)
	}
	if value, ok := tmuo.mutation.Label(); ok {
		_spec.SetField(ticketmodel.FieldLabel, field.TypeString, value)
	}
	if value, ok := tmuo.mutation.AssigneeID(); ok {
		_spec.SetField(ticketmodel.FieldAssigneeID, field.TypeUUID, value)
	}
	if value, ok := tmuo.mutation.Severity(); ok {
		_spec.SetField(ticketmodel.FieldSeverity, field.TypeInt, value)
	}
	if value, ok := tmuo.mutation.AddedSeverity(); ok {
		_spec.AddField(ticketmodel.FieldSeverity, field.TypeInt, value)
	}
	if value, ok := tmuo.mutation.Status(); ok {
		_spec.SetField(ticketmodel.FieldStatus, field.TypeInt, value)
	}
	if value, ok := tmuo.mutation.AddedStatus(); ok {
		_spec.AddField(ticketmodel.FieldStatus, field.TypeInt, value)
	}
	if value, ok := tmuo.mutation.Time(); ok {
		_spec.SetField(ticketmodel.FieldTime, field.TypeTime, value)
	}
	_node = &TicketModel{config: tmuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, tmuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{ticketmodel.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	tmuo.mutation.done = true
	return _node, nil
}
